name: Project quality check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  quality:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test
        ports:
          - 5432:5432

    steps:
      - name: Install curl and bash
        run: sudo apt-get update && sudo apt-get install -y curl bash

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3' # Remplacez par la version de PHP que vous utilisez
          tools: composer

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Security
        run: composer audit

      - name: Run PHP CodeSniffer
        run: vendor/bin/phpcs src/

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse

      - name: Wait for PostgreSQL to be ready
        run: sleep 15

      - name: Run PHPUnit
        env:
          DB_HOST: 127.0.0.1
          DB_DATABASE: test
          DB_USERNAME: postgres
          DB_PASSWORD: password
          DB_PORT: 5432
        run: vendor/bin/phpunit --coverage-text --colors=never

      - name: Check Composer Security Vulnerabilities
        run: symfony security:check

